"""initial_schema

Revision ID: 2b184b8c91ad
Revises: 
Create Date: 2026-08-10 15:10:06.448852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b184b8c91ad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('operator', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('resource', sa.String(length=200), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_operator'), 'audit_logs', ['operator'], unique=False)
    op.create_table('command_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vin', sa.String(length=17), nullable=False),
    sa.Column('command', sa.String(length=50), nullable=False),
    sa.Column('params', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('operator', sa.String(length=50), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_command_records_vin'), 'command_records', ['vin'], unique=False)
    op.create_table('dtc_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vin', sa.String(length=17), nullable=False),
    sa.Column('dtc_code', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=5), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('cleared_at', sa.DateTime(), nullable=True),
    sa.Column('snapshot_data', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dtc_records_dtc_code'), 'dtc_records', ['dtc_code'], unique=False)
    op.create_index(op.f('ix_dtc_records_vin'), 'dtc_records', ['vin'], unique=False)
    op.create_table('ota_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('software_version', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('strategy', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('target_vins', sa.Text(), nullable=False),
    sa.Column('completed_vins', sa.Text(), nullable=False),
    sa.Column('batch_plan', sa.Text(), nullable=False),
    sa.Column('vehicle_progress', sa.Text(), nullable=False),
    sa.Column('progress_percent', sa.Float(), nullable=False),
    sa.Column('current_batch', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telemetry_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vin', sa.String(length=17), nullable=False),
    sa.Column('metric', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_records_metric'), 'telemetry_records', ['metric'], unique=False)
    op.create_index(op.f('ix_telemetry_records_timestamp'), 'telemetry_records', ['timestamp'], unique=False)
    op.create_index(op.f('ix_telemetry_records_vin'), 'telemetry_records', ['vin'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vin', sa.String(length=17), nullable=False),
    sa.Column('plate_no', sa.String(length=20), nullable=False),
    sa.Column('oem', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('powertrain_type', sa.String(length=10), nullable=False),
    sa.Column('battery_capacity_kwh', sa.Float(), nullable=False),
    sa.Column('max_speed', sa.Float(), nullable=False),
    sa.Column('protocol_type', sa.String(length=20), nullable=False),
    sa.Column('vehicle_category', sa.String(length=30), nullable=False),
    sa.Column('fuel_type', sa.String(length=20), nullable=False),
    sa.Column('driver_name', sa.String(length=50), nullable=False),
    sa.Column('driver_ic', sa.String(length=30), nullable=False),
    sa.Column('online_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_vin'), 'vehicles', ['vin'], unique=True)
    op.create_table('work_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vin', sa.String(length=17), nullable=False),
    sa.Column('plate_no', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('diagnosis_result', sa.Text(), nullable=True),
    sa.Column('suggested_parts', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('assigned_to', sa.String(length=50), nullable=True),
    sa.Column('station', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_orders_vin'), 'work_orders', ['vin'], unique=False)
    op.create_table('vehicle_twins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('vin', sa.String(length=17), nullable=False),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('mileage', sa.Float(), nullable=False),
    sa.Column('soc', sa.Float(), nullable=False),
    sa.Column('soh', sa.Float(), nullable=False),
    sa.Column('battery_voltage', sa.Float(), nullable=False),
    sa.Column('battery_current', sa.Float(), nullable=False),
    sa.Column('max_cell_temp', sa.Float(), nullable=False),
    sa.Column('min_cell_temp', sa.Float(), nullable=False),
    sa.Column('insulation_resistance', sa.Float(), nullable=False),
    sa.Column('motor_speed', sa.Float(), nullable=False),
    sa.Column('motor_torque', sa.Float(), nullable=False),
    sa.Column('motor_temp', sa.Float(), nullable=False),
    sa.Column('gps_lng', sa.Float(), nullable=False),
    sa.Column('gps_lat', sa.Float(), nullable=False),
    sa.Column('alarm_level', sa.Integer(), nullable=False),
    sa.Column('active_dtcs', sa.Text(), nullable=False),
    sa.Column('fuel_level', sa.Float(), nullable=False),
    sa.Column('fuel_consumption', sa.Float(), nullable=False),
    sa.Column('engine_rpm', sa.Float(), nullable=False),
    sa.Column('coolant_temp', sa.Float(), nullable=False),
    sa.Column('oil_pressure', sa.Float(), nullable=False),
    sa.Column('cargo_status', sa.String(length=20), nullable=False),
    sa.Column('video_channels', sa.Integer(), nullable=False),
    sa.Column('acc_status', sa.String(length=10), nullable=False),
    sa.Column('last_report_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_id')
    )
    op.create_index(op.f('ix_vehicle_twins_vin'), 'vehicle_twins', ['vin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_twins_vin'), table_name='vehicle_twins')
    op.drop_table('vehicle_twins')
    op.drop_index(op.f('ix_work_orders_vin'), table_name='work_orders')
    op.drop_table('work_orders')
    op.drop_index(op.f('ix_vehicles_vin'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_telemetry_records_vin'), table_name='telemetry_records')
    op.drop_index(op.f('ix_telemetry_records_timestamp'), table_name='telemetry_records')
    op.drop_index(op.f('ix_telemetry_records_metric'), table_name='telemetry_records')
    op.drop_table('telemetry_records')
    op.drop_table('ota_tasks')
    op.drop_index(op.f('ix_dtc_records_vin'), table_name='dtc_records')
    op.drop_index(op.f('ix_dtc_records_dtc_code'), table_name='dtc_records')
    op.drop_table('dtc_records')
    op.drop_index(op.f('ix_command_records_vin'), table_name='command_records')
    op.drop_table('command_records')
    op.drop_index(op.f('ix_audit_logs_operator'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
